# Generated by Django 3.2 on 2021-05-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_product_id_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_active',
            new_name='is_active',
        ),
    ]
